### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by pat-flew** [erlandranvinge/ntlm.js#2]
Hi there! I was wondering if there is a reason why the auth requests are made synchronously rather than async? I am in a situation where I need to make the requests async so wondering if this is deliberate

**Comment by erlandranvinge** [comment]
Hi! Nope, not deliberate; more less random. 

To give you a bit of background, this project was somewhat of a saturday-hack where I was learning the details of this ancient model of authentication while seeing if this was actually possible to reimplement it bottom-up. Most browsers have NTLM-challenge response builtin for "normal" HTTP-requests, but I hadn't seen it done with AJAX before. As time went by people started using it, especially developers stuck in an unforgiving domain (I'm looking at you random enterprise product with your own markup and no viable way of customisation except injecting javascript).  

I haven't looked at the code in a while, but if I remember correctly it should be straight-forward to asyncify it by simply changing the XHR-requests to async and accepting a callback into the auth method. All PR:s are certainly welcome.
